name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm run setup
    
    - name: Run backend linting
      run: cd src/backend && npm run lint
      continue-on-error: true
    
    - name: Run frontend linting
      run: cd src/frontend && npm run lint
      continue-on-error: true
    
    - name: Build backend
      run: cd src/backend && npm run build
    
    - name: Build frontend
      run: cd src/frontend && npm run build
    
    - name: Run backend tests
      run: cd src/backend && npm test
      continue-on-error: true
    
    - name: Run frontend tests
      run: cd src/frontend && npm test
      continue-on-error: true

  security:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Run security audit
      run: |
        cd src/backend && npm audit --audit-level moderate
        cd ../frontend && npm audit --audit-level moderate
      continue-on-error: true
    
    - name: Run dependency check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'project-tracker'
        path: '.'
        format: 'ALL'
      continue-on-error: true

  deploy:
    runs-on: ubuntu-latest
    needs: [test, security]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to staging
      run: |
        echo "Deploying to staging environment..."
        # Add deployment commands here
    
    - name: Deploy to production
      if: github.event_name == 'push'
      run: |
        echo "Deploying to production environment..."
        # Add production deployment commands here